# Generated by Django 3.1 on 2023-06-23 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='hotel'),
            preserve_default=False,
        ),
    ]
