# Generated by Django 3.1 on 2023-06-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='bé pkota katolioque', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='localisation',
            field=models.CharField(default='lomé', max_length=100),
        ),
    ]
