# Generated by Django 4.1.7 on 2023-04-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='serie',
            field=models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('F4', 'F4'), ('D', 'D'), ('E', 'E'), ('C4', 'C4'), ('F2', 'F2'), ('A4', 'A4')], default=None, max_length=10),
        ),
    ]
